spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice_dev_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 104056

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create-drop

  messages:
    basename: il8n/exception
    encoding: UTF-8

  jwt:
    secret: govlepel@$&amp;
